version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  sponsors-receiver:
    lang: node20
    handler: ./sponsors-receiver
    image: ${SERVER:-docker.io}/${OWNER:-alexellis2}/sponsors-receiver:${TAG:-0.2.1}
    environment:
      write_debug: true
      RAW_BODY: true
    labels:
      com.openfaas.scale.zero: false
    secrets:
    - discord-sponsors-url
    - sponsors-webhook-secret
