name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get faas-cli
        uses: alexellis/arkade-get@master
        with:
          faas-cli: latest
      - name: Get templates
        run: faas-cli template store pull node20

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get TAG
        id: get_tag
        run: echo "TAG=latest-dev" >> $GITHUB_OUTPUT
      - name: Get Repo Owner
        id: get_repo_owner
        run: |
          repo_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          echo "repo_owner=${repo_owner}" >> $GITHUB_OUTPUT
      - name: Publish functions
        run: >
          OWNER="${{ steps.get_repo_owner.outputs.repo_owner }}" 
          TAG="latest"
          faas-cli build
